version: '3.8'

services:
  cloudpaste:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: cloudpaste:latest
    container_name: cloudpaste
    restart: unless-stopped

    # 只需要映射一个目录！
    volumes:
      - ./data:/cloudpaste

    # 暴露端口
    ports:
      - "8811:5280"

  
